version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: Install Allure
          command: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository -y ppa:qameta/allure
            sudo apt-get update
            sudo apt-get install allure
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
      - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest tests/windy_test.py --junitxml=test-reports/results.xml --alluredir=allure_reports
      - run:
          command: |
            . venv/bin/activate
            allure serve allure_reports
      - store_artifacts:
          path: selene-reports
      - store_artifacts:
          path: allure_reports
      - store_test_results:
          path: test-reports

workflows:
   version: 2
   commit:
     jobs:
      - build
   nightly:
     triggers:
       - schedule:
          # 4am UTC
          cron: "0 04 * * *"
          filters:
            branches:
              only: master
     jobs:
       - build